### ISSUE TITLE
Make a help function 

### ISSUE THREAD

**Issue by Rishikeshrajrxl** [FOSS-Cell-GECPKD/Todo-List#3]
In side main.Cpp file make a function call to help(). 
Write definition of help() above the int main(). 
Void help()
{
}
This help function should display these following on the console. 

•••••••••••••Welcome to To do List•••••••••••••••

              1. Add a new to do
              2. Show remaining todos
              3. Delete a todo
              4. Complete a todo
              5. Statistics
              6. Exit
                 
••••••••••••••••••••••••••••••••••••••••••••••••••••••••

**Comment by AmalChandru** [comment]
Hey, I am interested. Can I look into it?

**Comment by AmalChandru** [comment]
Created the P R .

**Comment by Rishikeshrajrxl** [comment]
> Created the P R .

You should wait until I don't assign the issue.

**Comment by Rishikeshrajrxl** [comment]
we are changing the workflow of this project ,
